### ISSUE TITLE
useParam always returns the same value (the first selected)

### ISSUE THREAD

**Issue by rodbs** [nandorojo/solito#75] opened 2022-05-31 16:39 UTC
I've got  a blog/[slug].js structure

In react navigation I have
```
 <NavigationContainer
        linking={useMemo(
          () => ({
            prefixes: [Linking.createURL('/')],
            config: {
              initialRouteName: 'home',
              screens: {
                HomeScreen: '',
                BlogScreen: 'blog',
                BlogSlugScreen: 'blog/:slug',
                CourseSlugScreen: ':courseSlug/:categorySlug/:slug',
...
```

In the Blog screen I have:
```
import { createParam } from 'solito'
const { useParam } = createParam() 

export function BlogSlugScreen({   route }) {
  const [slug] = useParam('slug')
   console.log('slug', slug)
   console.log('route', route)
   ...
```
So, first time a select a post, `slug`  keeps the right value and same thing for `route.params.slug`.
But next times, `route.params.slug`  stores the right value while `slug` keeps storing the first selected (it's not updated). Is it a bug ?

**Comment by nandorojo** [comment] 2022-05-31 16:46
i believe this is a duplicate of #51

**Comment by nandorojo** [comment] 2022-05-31 16:47
if you use setSlug it would work for now, as shown in the docs

**Comment by nandorojo** [comment] 2022-05-31 16:47
but yeah i need to fix this

**Comment by nandorojo** [comment] 2022-05-31 17:07
I mean use the setter from the `useParam` docs:

```
const [slug, setSlug] = useParam('slug')

// and then...

setSlug('123')
```

But this will be fixed when I have time.

**Comment by rodbs** [comment] 2022-05-31 17:19
ok , I understand. Thx!!

**Comment by nandorojo** [comment] 2022-07-02 21:50
closing as duplicate of #51

**Closed by nandorojo** 2022-07-02 21:50 UTC
