### ISSUE TITLE
Error Cannot use import statement outside a module - expo-router template

### ISSUE THREAD

**Issue by liteupmedia** [nandorojo/solito#356] opened 2023-03-17 03:35 UTC
Hi Fernando, I'm getting the following error when running any of the latest template, any idea what could be the issue?

Steps to reproduce: 
1 - `npx create-solito-app@latest my-solito-app -t with-expo-router`
2 - `cd my-solito-app`
3 - `yarn`
4 - `yarn web`
5 - Navigate to localhost:3000

```
error - /Users/{user}/source/repos/my-solito-app/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

Cheers

**Comment by nandorojo** [comment] 2023-03-17 03:55
hmm that’s odd. i’ll try to take a look tomorrow

**Comment by nandorojo** [comment] 2023-03-17 03:55
seems related to `transpilePackages`

**Comment by mnishihan** [comment] 2023-03-17 17:43
I'm facing the same issue for project created with following command:

```
npx create-solito-app@latest solito-nativewind -t with-tailwind
```
As this was my first tryout with Solito, I was wondering whether it would work for any earlier version than `create-solito-app@latest`??

**Comment by nandorojo** [comment] 2023-03-17 17:49
sorry i know this is frustrating, but not at the moment. the version is only of the CLI, not of the example itself. can you try adding `nativewind` to your `transpilePackages`?

**Comment by mnishihan** [comment] 2023-03-17 18:28
Adding `nativewind` to `transpilePackages` option in `apps/next/next.config.js` had no effect. The error remains same. :-(

**Comment by nandorojo** [comment] 2023-03-17 18:42
i think i see the issue. try moving react-native-web into the package.json of apps/next

**Comment by nandorojo** [comment] 2023-03-17 18:48
if that works, i think it’s due to the yarn 3 upgrade not hoisting RNW

**Comment by mnishihan** [comment] 2023-03-17 18:49
> i think i see the issue. try moving react-native-web into the package.json of apps/next

Moving!! From where? Interestingly, I cannot find any reference of `react-native-web` in any of the `package.json` files.

I'm adding it in `apps/next/package.json` and trying `yarn install` from root as you suggested. I'll let you know the result soon.

**Comment by mnishihan** [comment] 2023-03-17 18:50
> > i think i see the issue. try moving react-native-web into the package.json of apps/next
> 
> Moving!! From where? Interestingly, I cannot find any reference of `react-native-web` in any of the `package.json` files.
> 
> I'm adding it in `apps/next/package.json` and trying `yarn install` from root as you suggested. I'll let you know the result soon.

Nope! Still same error.

**Comment by nandorojo** [comment] 2023-03-17 18:52
🧐 

and if you delete `.next`? is react-native-web resolving in one of the node modules folders?

**Comment by derek-primumco** [comment] 2023-03-17 18:53
You may have to manually `rm -rf node_modules` and/or run `yarn cache clean` and/or delete the `.yarn` directory when debugging hoisting issues.

**Comment by mnishihan** [comment] 2023-03-17 19:07
> and if you delete .next? is react-native-web resolving in one of the node modules folders?

@nandorojo Deleting .next had no effect.  Yes, react-native-web is resolved into top level node_modules folder.

> You may have to manually `rm -rf node_modules` and/or run `yarn cache clean` and/or delete the `.yarn` directory when debugging hoisting issues.

@derek-primumco I tried all of these, but nothing has changed.

**Comment by nandorojo** [comment] 2023-03-17 19:11
can you try removing the lock file and running yarn?

**Comment by mnishihan** [comment] 2023-03-17 19:12
Hmm. That I haven't tried yet. Getting back to you soon.

**Comment by nandorojo** [comment] 2023-03-17 19:14
i managed to reproduce it, i'll have to see what's up later

**Comment by nandorojo** [comment] 2023-03-17 19:14
the blank template works for what it's worth, so that's a good reference

**Comment by mnishihan** [comment] 2023-03-17 19:19
> can you try removing the lock file and running yarn?

FYI, removing `yarn.lock` file didn't help either.

**Comment by nandorojo** [comment] 2023-03-17 19:21
it's as if the alias just isn't working for react-native

**Comment by nandorojo** [comment] 2023-03-17 19:24
fixed it. add `'react-native-gesture-handler'` to transpile modules

**Comment by nandorojo** [comment] 2023-03-17 19:24
always important to share the **full stack trace**, as this was visible at the bottom

**Comment by mnishihan** [comment] 2023-03-17 19:31
> always important to share the **full stack trace**, as this was visible at the bottom

'react-native-gesture-handler' was never In my stack trace, and the stack trace is still same as below from the very beginning. 

```
error - /Users/shihan/workspace/solito/solito_nativewind/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/shihan/workspace/solito/solito_nativewind/node_modules/nativewind/dist/styled/use-interaction.js:5:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/shihan/workspace/solito/solito_nativewind/node_modules/nativewind/dist/styled/index.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/shihan/workspace/solito/solito_nativewind/node_modules/nativewind/dist/index.js:18:14)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.nativewind (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:5048:18)
    at __webpack_require__ (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../packages/app/design/typography.tsx:14:68)
    at Object.../../packages/app/design/typography.tsx (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:4807:1)
    at __webpack_require__ (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///../../packages/app/features/home/screen.tsx:8:79)
    at Function.__webpack_require__.a (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///../../packages/app/features/home/screen.tsx:1:21)
    at Object.../../packages/app/features/home/screen.tsx (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:4829:1)
    at __webpack_require__ (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/index.tsx:6:82)
    at Function.__webpack_require__.a (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/webpack-runtime.js:97:13)
    at eval (webpack-internal:///./pages/index.tsx:1:21)
    at Object../pages/index.tsx (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:44:1)
    at __webpack_require__ (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/webpack-runtime.js:33:42)
    at __webpack_exec__ (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:5398:39)
    at /Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:5399:28
    at Object.<anonymous> (/Users/shihan/workspace/solito/solito_nativewind/apps/next/.next/server/pages/index.js:5402:3)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  page: '/'
}
wait  - compiling /_error (client and server)...
```

**Comment by mnishihan** [comment] 2023-03-17 19:31
Anyway, its very late here in my country. I'll try everything from scratch tomorrow again.

Thanks a lot for your time & quick support. 👍

**Comment by nandorojo** [comment] 2023-03-18 02:07
odd, yeah if you could try running the starter repo again it should work

**Comment by studigen** [comment] 2023-03-18 02:31
on native side getting following error. but app working.

```
 ERROR  [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.0.2 vs. 2.14.4). Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must downgrade to 2.14.4 which is bundled into Expo SDK.
```

**Comment by nandorojo** [comment] 2023-03-18 02:35
did you read the error and proceed accordingly? you need an expo dev client for reanimated 3

**Comment by studigen** [comment] 2023-03-18 02:40
yes, If the version downgrade to `2.14.4`, the error message disappear.

**Comment by studigen** [comment] 2023-03-18 02:44
of course, installed expo sdk version is 48.0.0

**Comment by studigen** [comment] 2023-03-18 02:47
and following error occur on web side.

```
../../node_modules/react-native-animatable/createAnimatableComponent.js
Module parse failed: Unexpected token (599:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Animatable
|           ref={this.handleRef}
|           style={[
```

**Comment by nandorojo** [comment] 2023-03-18 02:57
you need to add that library to transpile modules if you want to use it on web. but i’d just use moti anyway. please see the 3.1 release notes.

**Comment by studigen** [comment] 2023-03-18 03:08
i already added. could I have missed something?

```
const { withExpo } = require('@expo/next-adapter')

/** @type {import('next').NextConfig} */
const nextConfig = {
	// reanimated (and thus, Moti) doesn't work with strict mode currently...
	// https://github.com/nandorojo/moti/issues/224
	// https://github.com/necolas/react-native-web/pull/2330
	// https://github.com/nandorojo/moti/issues/224
	// once that gets fixed, set this back to true
	reactStrictMode: false,
	transpilePackages: [
		'react-native',
		'react-native-web',
		'react-native-svg',
		'native-base',
		'solito',
		'dripsy',
		'@dripsy/core',
		'moti',
		'app',
		'react-native-reanimated',
		'@expo/html-elements',
		'react-native-gesture-handler',
	],
}

module.exports = withExpo(nextConfig)

```

**Comment by nandorojo** [comment] 2023-03-18 03:10
yes, you didn’t add it. the error is `react-native-animatable`

**Comment by studigen** [comment] 2023-03-18 03:18
oh sorry. `react-native-reanimated` I thought that was it.

after added it, i get this error like the issue above.

```
error - /Users/foo/Documents/_Work_/bridge-client/node_modules/react-native/index.js:14
import typeof AccessibilityInfo from './Libraries/Components/AccessibilityInfo/AccessibilityInfo';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1149:20)
    at Module._compile (node:internal/modules/cjs/loader:1190:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
```

**Comment by mnishihan** [comment] 2023-03-19 07:38
@nandorojo Looks like I could trace & fix this issue for `with-tailwind` template. I've created a PR #358 for review with the required changes. 

And IMHO, if the same changes are implemented, this issue should be fixed for other templates as well.

**Comment by nandorojo** [comment] 2023-03-20 01:30
I left some notes on your PR

**Comment by studigen** [comment] 2023-03-20 02:02
https://github.com/mnishihan/solito/commit/2bc0f967a5772d0031bb97893ddea45649c515a7 this patch not working on `with-expo-router` template

**Comment by sunnychaganty** [comment] 2023-03-22 03:28
Can confirm that none of these steps are working with-expo-router. The app just crashes without any warning or message or stack in the terminal for `yarn native` seems like `yarn web` works fine

**Comment by nandorojo** [comment] 2023-03-22 03:37
interesting, are there any useful logs? did you do the expo dev client as the 3.1 release notes indicate, rather than expo go?

**Comment by sunnychaganty** [comment] 2023-03-22 04:21
I am using the Solito starter for Expo Router & just running the installed apps & while the app build, opening in Expo Go does crash even if I change to` expo start` rather than `expo start --dev-client`
Did not understand the 3.1 release notes you are referring to - but I am assuming this is for setting up Expo EAS for a development profile? I will try it in the morning.

**Comment by nandorojo** [comment] 2023-03-22 13:08
you need to use an expo dev client rather than expo go.

**Comment by sunnychaganty** [comment] 2023-03-22 20:29
> you need to use an expo dev client rather than expo go.

Could be the root why I am facing this issue - will try later this evening

**Comment by sunnychaganty** [comment] 2023-03-23 03:28
Ok - so using expo dev client - also fails with below, none of which is the actual application code AFAIK:
```

[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainActivity.java:19: error: package R does not exist
[stderr] 
    setTheme(R.style.AppTheme);
[stderr] 
              ^
[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainActivity.java:39: error: cannot find symbol
[stderr] 
    return new ReactActivityDelegateWrapper(this, BuildConfig.IS_NEW_ARCHITECTURE_ENABLED, new DefaultReactActivityDelegate(
[stderr] 
                                                  ^
[stderr] 
  symbol:   variable BuildConfig
[stderr] 
  location: class MainActivity
[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainApplication.java:26: error: cannot find symbol
[stderr] 
        return BuildConfig.DEBUG;
[stderr] 
               ^
[stderr] 
  symbol: variable BuildConfig
[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainApplication.java:45: error: cannot find symbol
[stderr] 
        return BuildConfig.IS_NEW_ARCHITECTURE_ENABLED;
[stderr] 
               ^
[stderr] 
  symbol: variable BuildConfig
[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainApplication.java:50: error: cannot find symbol
[stderr] 
        return BuildConfig.IS_HERMES_ENABLED;
[stderr] 
               ^
[stderr] 
  symbol: variable BuildConfig
[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainApplication.java:63: error: cannot find symbol
[stderr] 
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[stderr] 
        ^
[stderr] 
  symbol:   variable BuildConfig
[stderr] 
  location: class MainApplication
[stderr] 
/home/expo/workingdir/build/apps/expo/android/app/src/main/java/com//xxx/xxx/MainApplication.java:63: error: illegal parenthesized expression
[stderr] 
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
[stderr] 
       ^
[stderr] 
7 errors
```

**Comment by nandorojo** [comment] 2023-03-23 13:36
Fixed in the latest starter. If you run the script again, it'll work as long as you use an Expo Dev Client. Thanks!

**Comment by nandorojo** [comment] 2023-03-23 13:37
Closing this out as it's fixed now. See the release notes here if you'd like: https://github.com/nandorojo/solito/releases/tag/v3.1.1

**Closed by nandorojo** 2023-03-23 13:37 UTC
