### ISSUE TITLE
Failure to scaffold monorepo

### ISSUE THREAD

**Issue by jeffscottward** [nandorojo/solito#222] opened 2022-11-06 20:12 UTC
Fails in both examples with and without expo router

`npx create-solito-app@latest vertex.xyz`
`npx create-solito-app@latest -t with-expo-router vertex.xyz`

<img width="1143" alt="Screenshot 2022-11-06 at 3 10 54 PM" src="https://user-images.githubusercontent.com/1263486/200192792-d6f764aa-4086-44b8-87e4-31ca108b6c1f.png">

**Comment by nandorojo** [comment] 2022-11-06 20:20
I think this is a node 18 issue, duplicate of #219 #205

**Closed** 2022-11-06 20:22 UTC
