### ISSUE TITLE
Type Warning on SolitoImage

### ISSUE THREAD

**Issue by timothymiller** [nandorojo/solito#437] opened 2023-10-15 20:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Do you want this issue prioritized?

- [ ] Yes, I have sponsored
- [X] Not urgent

### Current Behavior

When using SolitoImage with a string src, it throws the following type warnings: 

## Implementation:
```ts
<SolitoImage src="/logo.png" width={96} height={96} alt="App Logo" />
```

## The warnings:

```ts
Type '{ src: string; width: number; height: number; alt: string; }' is not assignable to type 'IntrinsicAttributes & (SolitoImageProps & RefAttributes<Image>)'.

Type '{ src: string; width: number; height: number; alt: string; }' is missing the following properties from type 'Pick<any, "alt" | "blurDataURL" | "placeholder" | "loader" | "priority" | "loading" | "sizes" | "quality" | "crossOrigin" | "referrerPolicy" | "unoptimized">': blurDataURL, placeholder, loader, priority, and 6 more.ts(2322)
```

## Workaround
The implementation works corectly, and adding `@ts-ignore` will temporarily make the warning go away.

### Expected Behavior

The types on SolitoImage to not throw a warning when using an implementation from the docs.

### Versions

```markdown
- Solito: 4.0.1
- Next.js: 13.5.3
- Expo: 49.0.13
- React Native: 0.72.5
```

### Screenshots

<img width="867" alt="Screenshot 2023-10-15 at 16 38 14" src="https://github.com/nandorojo/solito/assets/46549361/c6a06a1e-3202-4bd5-a4f4-7c7a9e94f807">

**Comment by derek-primumco** [comment] 2023-10-16 20:19
You should use `@ts-expect-error The reason the error is a false alarm` instead of `@ts-ignore`. 

https://dev.to/maafaishal/ts-expect-error-over-ts-ignore-in-typescript-5140#:~:text=When%20you%20use%20%40ts%2Dignore,to%20ignore%20the%20type%20error.

ESLint rule:
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/ban-ts-comment.md#allow-with-description

**Comment by nandorojo** [comment] 2023-10-16 22:30
I wonder if you have `@types/react-native` installed or something that's messing this up

**Comment by nandorojo** [comment] 2023-10-16 22:32
I'm not able to reproduce this error. It works for me [on this playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgZQgG2DCBJEBDAcwFM4BfOAMyghDgHIBndTCAelEKLoChRJY4AJSJ4AxvCo16UEeJ7dREAHYN4AQTgBeOAAoAlFoB8cADyoMWXJzgMoozQCJWaCAQgA6MEoIO4Ad2AAExgAC00EAE4ANnIQomACEJhw6PI8NGSHNTAwOAAZVwhfVkNuIA).

**Comment by derek-primumco** [comment] 2023-10-16 22:53
@nandorojo I see it on that exact playground, although there was a rendering glitch for about 20 seconds while loading...
<img width="1024" alt="image" src="https://github.com/nandorojo/solito/assets/122907173/e66c7533-7609-4f2d-873c-f6e5e0b7dc64">

**Comment by nandorojo** [comment] 2023-10-16 22:55
![image](https://github.com/nandorojo/solito/assets/13172299/4e11fb03-d25f-4177-94dc-75fe9ee0bac3)

Works fine for me oddly

**Comment by nandorojo** [comment] 2023-10-16 22:55
The glitch is due to it downloading react

**Comment by derek-primumco** [comment] 2023-10-16 23:01
Well this line is the issue `src: Exclude<NextImageProps['src'], string> | number` 🤷

**Comment by nandorojo** [comment] 2023-10-16 23:10
I wonder if it’s from a new version of next changing types?

**Comment by nandorojo** [comment] 2023-10-16 23:11
Oddly I haven’t reproduced it yet

**Comment by derek-primumco** [comment] 2023-10-16 23:14
Possibly. I haven't tried to debug it.

But I can confirm that we've seen this live in our codebase for months.

<img width="621" alt="image" src="https://github.com/nandorojo/solito/assets/122907173/cc43c0d3-435a-4615-ba34-bee08aaebe31">

<img width="618" alt="image" src="https://github.com/nandorojo/solito/assets/122907173/5b936ad7-880f-4b1d-b9b0-b5fb2c107665">

This is with `"solito": "^4.0.1",` confirmed 4.0.1 in `yarn.lock`.

**Comment by derek-primumco** [comment] 2023-10-16 23:15
Also my previous comment wasn't the least bit off-topic -- to use Solito in a production environment, you absolutely need to be using `@ts-expect-error`. If you think it's off-topic, then I'll stop contributing now. Thanks

**Comment by nandorojo** [comment] 2023-10-16 23:28
Hiding it wasn’t meant as a slight, I’m simply trying to guide the conversation of issues towards identifying the problem.

I marked it as off-topic because it was just stating a different TypeScript comment to silence the error and came off as a proposed solution.

For what it’s worth, I also prefer ts-expect-error over ts-ignore to encourage correctness when fixes are released. That said, I’ve heard it’s supposed to compile a bit slower than ts-ignore and didn’t directly get to the heart of the issue.

> If you think it's off-topic, then I'll stop contributing now. 

I think we should start over a bit here because it wasn’t my intention to make you feel that way. I have dozens GitHub notifications per hour that I try to respond to promptly, and part of that is just triaging comments to make sure they are key to solving the issue. 

> But I can confirm that we've seen this live in our codebase for months.

If it’s been in your codebase for months, I’d like to get it solved. I was under the impression that this was fixed for a while (since it’s worked for us and others on Discord).

**Comment by nandorojo** [comment] 2023-10-16 23:32
In any case, I unhid @derek-primumco’s comment, but above all it would be great to find out where the root of this issue is and I’d be happy to merge a PR.

**Comment by nandorojo** [comment] 2023-10-17 02:09
<img width="799" alt="image" src="https://github.com/nandorojo/solito/assets/13172299/46a55026-c255-4905-9a88-37b48c6894b2">

Hey guys, I'm still struggling to repro this...here it is in app code.

**Comment by nandorojo** [comment] 2023-10-17 14:04
Here is an example of it working for me: https://github.com/nandorojo/solito-437-repro

I tried upgrading Next to latest and that worked too.

Can you guys try removing `@types/react-native` from any `package.json` you might have and make sure you're on RN 0.72+?

If you can create a reproduction showing this working I can take a look. However, I am simply not able to reproduce it for some reason.

Can you also make sure you're on a recent version of Expo?

**Comment by nandorojo** [comment] 2023-10-17 14:06
> Possibly. I haven't tried to debug it.
> 
> But I can confirm that we've seen this live in our codebase for months.
> 
> `with @ts-expect-error` <img alt="image" width="621" src="https://user-images.githubusercontent.com/122907173/275669232-cc43c0d3-435a-4615-ba34-bee08aaebe31.png">
> 
> `without @ts-expect-error` <img alt="image" width="618" src="https://user-images.githubusercontent.com/122907173/275669254-5b936ad7-880f-4b1d-b9b0-b5fb2c107665.png">
> 
> This is with `"solito": "^4.0.1",` confirmed 4.0.1 in `yarn.lock`.

@derek-primumco can you post the full code? Hard to debug from just that.

**Comment by nandorojo** [comment] 2023-10-17 14:09
@timothymiller your code is showing this error:

```sh
Type '{ src: string; width: number; height: number; alt: string; }' is missing the following properties from type 'Pick<any, "alt" | "blurDataURL" | "placeholder" | "loader" | "priority" | "loading" | "sizes" | "quality" | "crossOrigin" | "referrerPolicy" | "unoptimized">': blurDataURL, placeholder, loader, priority, and 6 more.ts(2322)
```

Something is clearly wrong here, because it's saying `from Pick<any` which would indicate some type isn't getting loaded for you. What happens if you run `yarn why next` and `yarn why expo-image`? Did you run `yarn install` in the root of your repository?

**Comment by nandorojo** [comment] 2023-10-17 14:12
These are the props in question where the warning is thrown. It seems like Next.js is not getting properly installed in your package. Please confirm the results of `yarn why next` – I have a feeling this may not be a Solito starter? Or maybe you need to run `yarn install` in the root.

<img width="819" alt="Screenshot 2023-10-17 at 10 10 25 AM" src="https://github.com/nandorojo/solito/assets/13172299/8fd55eed-4b81-4a88-9e62-29beafe7da2a">

As for @derek-primumco's case, which is odd to me, it may be due to wrapping SolitoImage in such a way where the props it receives will be ambiguous, as opposed to simply spreading the props. If I see the code it's probably an easy fix.

**Closed** 2023-10-19 15:29 UTC

**Comment by apetta** [comment] 2023-11-29 09:25
For me, ensuring `expo-image` was installed in the expo project resolved this error. 

For what its worth, you do get a glimpse of the error on the playground @nandorojo shared, but it's just while it's figuring out the dependencies:
![Screenshot 2023-11-29 at 09 04 40](https://github.com/nandorojo/solito/assets/33671231/b60a5cde-53a9-4f60-91dd-52874495db64)

I think ensuring all dependencies are installed on both next/expo sides of your project should resolve this error - especially if you're not using a Solito starter.

**Comment by joshuaobrien** [comment] 2024-01-10 04:49
I was experiencing this error, but ensuring `expo-image` was installed in the expo project resolved it for me too 👍. Looks like I missed that when setting up my project.

**Comment by HaythemLazaar** [comment] 2024-01-11 21:03
I had the same error, I had to install `expo-image` in the Next.js project as mentioned above.

**Comment by nandorojo** [comment] 2024-02-10 00:18
In case anyone faces an issue even after installing `expo-image`, you might try this with each file type you use:

```ts
// image.d.ts
declare module '*.png' {
  const value: any
  export default value
}
```
